package co.unal.camd.ga.haea.old;

import co.unal.camd.properties.estimation.GeneticOperator;
import co.unal.camd.properties.estimation.Molecule;
import co.unal.camd.properties.estimation.old.OldMoleculesEnvironment;
import unalcol.evolution.Environment;
import unalcol.evolution.Individual;
import unalcol.evolution.Population;

import java.util.*;

/**
 */
public class OldMoleculeMutation extends GeneticOperator {

    public OldMoleculeMutation(Environment _environment) {
        super(_environment);
    }

    public Vector<Molecule> apply(Molecule genome) {
        //System.out.println("Mutation");
        Molecule clone_genome = genome.clone(); // @TODO: clonar objeto
        // TODO: Mutacion

        int num = (int) (Math.random() * (clone_genome.getTotalGroups() - 1));
        searchAndReplace(clone_genome.getMoleculeByRootGroup(), num, false, ((OldMoleculesEnvironment) environment).aGC);
        Vector<Molecule> v = new Vector<Molecule>();
        v.add(clone_genome);
        return v;
    }

    /**
     * Apply the operator over the given individuals
     *
     * @param population Source population
     * @param x          Individual used as first parent
     * @return A collection of individuals generated by the operator
     */
    public Vector<Individual> apply(Population population, int x) {
        Vector<Individual> v = null;
        if (population != null) {
            v = new Vector<Individual>();
            Molecule genome = (Molecule) population.get(x).getGenome();
            Vector<Molecule> genomes = apply(genome);
            int n = genomes.size();
            for (int i = 0; i < n; i++) {
                v.add(new Individual(genomes.get(i)));
            }
        }
        return v;
    }

    /**
     * Return the genetic operator arity
     *
     * @return the genetic operator arity
     */
    public int getArity() {
        return 1;
    }

}
