package co.unal.camd.properties.estimation;

import co.unal.camd.ga.haea.MoleculeGenotype;
import unalcol.evolution.Environment;
import unalcol.evolution.Individual;
import unalcol.evolution.Population;

import java.util.Vector;

public class CutAndReplace extends GeneticOperator {

    public CutAndReplace(Environment _environment) {
        super(_environment);
    }

    public Vector<Molecules> apply(Molecules genome) {
        //System.out.println("CutAndReplace");
        Molecules clone_genome = genome.clone(); // @TODO: clonar objeto
        // TODO: Mutacion
        int num = (int) (Math.random() * (clone_genome.getTotalGroups()) - 1);

        int valence = (int) (Math.random() * 3) + 2;
        boolean functional = false;

        FunctionalGroupNode aGroupMut = clone_genome.getGroupAt(num);
        if (aGroupMut.getRootNode() > 4) {
            functional = true;
        }
        int refCode = MoleculeGenotype.getNewRefCode(valence, ((MoleculesEnviroment) environment).aGC, functional);
        FunctionalGroupNode newGroup = new FunctionalGroupNode(refCode);

        if (valence == 3) {
            newGroup.addGroup(new FunctionalGroupNode(1));
        } else if (valence == 4) {
            newGroup.addGroup(new FunctionalGroupNode(1));
            newGroup.addGroup(new FunctionalGroupNode(1));
        }
        searchAndReplace(clone_genome.getMoleculeByRootGroup(), num, newGroup, false, ((MoleculesEnviroment) environment).aGC);
        Vector<Molecules> v = new Vector<Molecules>();
        v.add(clone_genome);
        return v;
    }

    /**
     * Apply the operator over the given individuals
     *
     * @param population Source population
     * @param x          Individual used as first parent
     * @return A collection of individuals generated by the operator
     */
    public Vector<Individual> apply(Population population, int x) {
        Vector<Individual> v = null;
        if (population != null) {
            v = new Vector<Individual>();
            Molecules genome = (Molecules) population.get(x).getGenome();
            Vector<Molecules> genomes = apply(genome);
            int n = genomes.size();
            for (int i = 0; i < n; i++) {
                v.add(new Individual(genomes.get(i)));
            }
        }
        return v;
    }

    /**
     * Return the genetic operator arity
     *
     * @return the genetic operator arity
     */
    public int getArity() {
        return 1;
    }


}
